stages:
  - build
  - test
  - deploy

variables:
  DJANGO_SETTINGS_MODULE: "streamingapp.settings"
  DATABASE_URL: "sqlite:///db.sqlite3"  # اگر از دیتابیس دیگری استفاده می‌کنید این را تغییر دهید

build:
  stage: build
  image: python:3.10
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python manage.py collectstatic --noinput

test:
  stage: test
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - python manage.py check

deploy:
  stage: deploy
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - python manage.py migrate
    - python manage.py runserver 0.0.0.0:8000
