# Generated by Django 4.2.6 on 2023-11-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.TextField()),
                ("segmentedPath", models.TextField()),
                ("errorFrame", models.TextField()),
                ("eyeCenter", models.TextField()),
                ("needleCenter", models.TextField()),
                ("operators", models.TextField()),
            ],
        ),
    ]
