# Generated by Django 4.2.6 on 2023-12-17 16:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("segment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processID", models.TextField(blank=True, null=True)),
                ("result", models.TextField(blank=True, null=True)),
                ("startTime", models.DateTimeField(default=datetime.datetime.now)),
                ("endTime", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name="video",
            name="eyeCenter",
        ),
        migrations.RemoveField(
            model_name="video",
            name="needleCenter",
        ),
        migrations.RemoveField(
            model_name="video",
            name="operators",
        ),
        migrations.AddField(
            model_name="video",
            name="process",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="segment.processdb",
            ),
        ),
    ]
