# Generated by Django 4.2.6 on 2024-07-19 05:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("segment", "0002_processdb_remove_video_eyecenter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotateVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.TextField()),
                ("time", models.DateTimeField(default=datetime.datetime.now)),
                ("duration", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.TextField()),
                ("duration", models.PositiveIntegerField(default=1)),
                ("data", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Annotate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("events", models.TextField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("sections", models.TextField(blank=True, null=True)),
                (
                    "videoID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="segment.annotatevideo",
                    ),
                ),
            ],
        ),
    ]
