# Generated by Django 5.1.3 on 2024-12-04 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodels',
            name='upload_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Upload Time'),
        ),
    ]
