# Generated by Django 5.1.3 on 2025-02-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunking', '0002_videomodels_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodels',
            name='end_time',
            field=models.IntegerField(default=0, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='videomodels',
            name='start_time',
            field=models.IntegerField(default=0, verbose_name='Start Time'),
        ),
    ]
